      - name: Build PlayCover
        run: |
          mkdir -p output

          xcodebuild \
            -project PlayCover.xcodeproj \
            -scheme PlayCover \
            -configuration Nightly \
            -destination 'generic/platform=macOS' \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="-" \
            DEVELOPMENT_TEAM="" \
            ARCHS=arm64 \
            ONLY_ACTIVE_ARCH=NO \
            build
